#numerical data types
#integers
#float
#complex
#boolean
#string
#bytes
#bytearray
#memoryview
#range
#list
#tuple
#set
#frozenset
#dict
#None
#Ellipsis
#NotImplemented
#True
#False
print(5)
print(55.6)
print(5+3j)
print(True)
print("Hello")
print(b"Hello")
print(bytearray(5))
print(memoryview(bytes(5)))
print(range(5))
print([1,2,3,4,5])
print((1,2,3,4,5))
print({1,2,3,4,5})
print(frozenset({1,2,3,4,5}))
print({"name":"John","age":30})
print(None)
print(Ellipsis)
print(NotImplemented)